---
# E: Discovery component allow to discover some devices automatically
# F: L'intégration `discovery` permet de detectéer certain équipements automatiquement.
#
# https://www.home-assistant.io/components/discovery/
#
discovery:
