---
# Logger to help debug
#
# https://www.home-assistant.io/components/logger/
#
logger:
  default: warning
# logs:
#    homeassistant.components.meteo_france: debug
#    custom_components.renaultze: debug
#    homeassistant.components.xiaomi_aqara: debug
#    custom_components.linky_custom: debug
#    homeassistant.components.recorder: debug
#    homeassistant.components.logbook: debug
#    homeassistant.components.zwave: warning
#    homeassistant.components.vacuum.xiaomi_miio: debug
