---
# Xiaomi Aqara is a smart home system by the Chinese Xiaomi.
# It uses Zigbee as its main protocol and requires a Xiaomi Aqara Gateway.
# This connects up the Gateway with Home Assistant.
#
# https://www.home-assistant.io/components/xiaomi_aqara/
#
xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret gateway_xiaomi
