---
# boolean to know if vacuum can clean the the room
#
# If yes the room will be cleaned today.
# As the living room is cleaned every workday in safe mode, set to no when done.
#
vacuum_can_clean_the_living_room_safe:
  name: Le salon peut être nettoyé en mode safe
