---
# boolean to know if vacuum can clean the the room
#
# If yes the room is setted to secure no obstacle will pertubate the vacuum.
# If no the room won't be cleaned during daily vacuum routine
#
vacuum_can_clean_the_carpet:
  name: Le tapis peut être nettoyé
