---
# boolean to know if vacuum can clean the the room
#
# If yes the room will be cleaned today.
# As the entrance is cleaned every workday, set to no when done.
#
vacuum_can_clean_the_entrance:
  name: L'entrée peut être nettoyée
