---
alias: debug_script
sequence:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.stop_deep_sleep
  - wait_template: "{{ is_state('input_boolean.stop_deep_sleep', 'on') }}"
