---
# EN: Notifications to monitor internal devices.
# FR: Notification pour surveillance des appareils de la maison.
#
# EN: One when detected down. Another when back online.
# FR: Une notification quand plus detectée. Un nouvelle quand de nouveau en ligne.
#
- alias: 'Notification de système KO'
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.google_home
      to: 'off'
    - platform: state
      entity_id: binary_sensor.NAS
      to: 'off'
    - platform: state
      entity_id: binary_sensor.rocky
      to: 'off'
    - platform: state
      entity_id: binary_sensor.esphome_pompe_piscine_status
      to: 'off'

  action:
    - service: notify.telegram
      data_template:
        message: >
          {{ trigger.to_state.attributes.friendly_name }} ne répond plus.
    - service: persistent_notification.create
      data_template:
        title: Un système est KO
        message: >-
          {{ trigger.to_state.attributes.friendly_name }} ne répond plus.
        notification_id: system_KO

- alias: "Notification système back online"
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.google_home
      to: 'on'
    - platform: state
      entity_id: binary_sensor.NAS
      to: 'on'
    - platform: state
      entity_id: binary_sensor.rocky
      to: 'on'
    - platform: state
      entity_id: binary_sensor.esphome_pompe_piscine_status
      to: 'on'

  action:
    - service: notify.telegram
      data_template:
        message: >
          {{ trigger.to_state.attributes.friendly_name }} is back online !.

- alias: "Notification memory left too low"
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.memory_use_percent
      above: 90
  action:
    - service: notify.telegram
      data_template:
        message: >
          Attention la mémoire utilisée à dépassé 90%.
    - service: persistent_notification.create
      data_template:
        title: Peu de mémoire disponible
        message: >-
          Attention la mémoire utilisée à dépassé 90%.
        notification_id: memomry_too_high
