---
# Automation to monitor my Renault Zoe
# Send notification when charge start or stop
#
# https://github.com/epenet/hassRenaultZE
#
- alias: notify_zoe_charge_start
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.zoe_charging
      to: 'on'
  action:
    - service: notify.telegram
      data_template:
        message: >
          La Zoé a commencé une charge à {{ states.sensor.zoe.state_with_unit }}.

- alias: notify_zoe_charge_end
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.zoe_charging
      to: 'off'
  action:
    - service: notify.telegram
      data_template:
        message: >
          La Zoé a terminé une charge à {{ states.sensor.zoe.state_with_unit }}.
