alias: Éteindre les lumières
hide_entity: true
trigger:
  platform: event
  event_type: telegram_callback
  event_data:
    data: /eteintLumiere
action:
- service: telegram_bot.answer_callback_query
  data_template:
    callback_query_id: '{{ trigger.event.data.id }}'
    message: J'éteins les lumières
- service: light.turn_off
  entity_id: light.salon
- service: telegram_bot.edit_message
  data_template:
    message_id: '{{ trigger.event.data.message.message_id }}'
    chat_id: '{{ trigger.event.data.user_id }}'
    message: 'Les lumières du salon sont éteintes'