---
# This binary motion sensor, allow to track if any of the sensors of the house
# detect a movement.
# Currently only one motion sensor live in the house.
#
# https://www.home-assistant.io/components/binary_sensor.template/
#
platform: template
sensors:
  motion_house_meta:
    friendly_name: "Mouvement dans la maison"
    device_class: motion
    value_template: >-
      {%- if is_state("binary_sensor.motion_sensor_livingroom", "on")
      -%}
      True
      {%- else -%}
      False
      {%- endif %}
