---
# This binary sensor, track the charging state of the Zoé
#
# https://github.com/epenet/hassRenaultZE
# https://www.home-assistant.io/components/binary_sensor.template/
#
platform: template
sensors:
  zoe_charging:
    friendly_name: "Charge en cours"
    value_template: >-
      {%- if is_state_attr('sensor.zoe', 'charging', true)
      -%}
      true
      {%- else -%}
      false
      {%- endif %}
    icon_template: >-
      {%- if is_state_attr('sensor.zoe', 'charging', true)
      -%}
      mdi:battery-charging-30
      {%- else -%}
      mdi:battery-30
      {%- endif %}
