---
esphome:
  name: capteur_piscine
  platform: ESP32
  board: lolin32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

api:
  password: !secret api_password

ota:
  password: !secret ota_password

# 1wire configuration
dallas:
  - id: dallas_hub1
    pin: 4
    update_interval: 1s

# Individual sensors
sensor:
  - platform: dallas
    dallas_id: "dallas_hub1"
    address: 0x9C0417C1A988FF28
    name: "Température Piscine"
    icon: "mdi:oil-temperature"

  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 20s

deep_sleep:
  # run_duration: 20s
  # sleep_duration: 1h
  run_duration: 30s
  sleep_duration: 1min
  id: deep_sleep_1

binary_sensor:
  # Node status in Home Assistant
  - platform: status
    name: "Capteur piscine"

  # get from HA a binary switch for pausing/resuming deep sleep
  - platform: homeassistant
    name: "Input Boolean From Home Assistant"
    entity_id: input_boolean.stop_deep_sleep
    on_press:
      then:
        - deep_sleep.prevent: deep_sleep_1
    on_release:
      then:
        - deep_sleep.enter: deep_sleep_1
