---
# Get information from UPC Backup
#
# https://www.home-assistant.io/integrations/nut
#
platform: nut
name: UPC Back-UPS
host: !secret local_ip_nas
resources:
  - ups.model
  - ups.status.display
  - ups.load
  - input.voltage
  - battery.runtime
