---
# Sensor to monitor error states of my Xiaomi Vacuum Cleaner.
# Integration in Telegram inspired by
# https://medium.com/@honcheng/how-i-got-my-vacuum-cleaner-to-talk-back-to-me-via-telegram-d4b471b7598c
#
# https://www.home-assistant.io/components/sensor.template/
#
platform: template
sensors:
  vacuum_cleaner_error_sensor:
    friendly_name: Vacuum Cleaner Error Sensor
    value_template: >-
      {% if states.vacuum.rocky.attributes.error is defined %}
        {{states.vacuum.rocky.attributes.error}}
      {% else %}
        No Error
      {% endif %}
