---
# Split attributes of vibration sensor
#
# No documentation
#
platform: template
sensors:
  vibration_test_tiltangle:
    value_template: >-
      {{ state_attr('binary_sensor.vibration_test', 'tiltangle') | int}}
    unit_of_measurement: "°"
