---
# Split attributes of vibration sensor
#
# No documentation
#
platform: template
sensors:
  vibration_test_orientation:
    value_template: >-
      {{ state_attr('binary_sensor.vibration_test', 'orientation')}}
