---
# Sensor to integrate the information of my Zoé by Renault
# Using custom component by epenet
#
# https://github.com/epenet/hassRenaultZE
#
platform: renaultze
name: Zoé
username: !secret renaultzoe_login
password: !secret renaultzoe_password
vin: !secret renaultzoe_vin
