---
# E: Sensor with date of the end of the Zoé charge
# F: Sensor avec la date de la fin de charge de la Zoé
#
#
platform: template
sensors:
  zoe_end_of_charge_time:
    value_template: >-
      {%  if state_attr('sensor.zoe','charging_remaining_time') is number  %}
      {{ (as_timestamp(state_attr('sensor.zoe','last_update'))
      + state_attr('sensor.zoe','charging_remaining_time')*60)
      | timestamp_custom('%Y-%m-%dT%H:%M:%S%z')}}
      {% endif %}
    availability_template: >-
      {%  if state_attr('sensor.zoe','charging_remaining_time') is number  %}
      true
      {% else %}
      false
      {% endif %}
    friendly_name: "date de fin de charge"
    icon_template: mdi:battery-charging-100
    device_class: timestamp
