---
# Curent mileage in the week.
#
# Reset on monday at 00h00
#
platform: template
sensors:
  zoe_curent_week_mileage:
    value_template: >-
      {% if state_attr('sensor.zoe' , 'mileage') is not none -%}
        {{ state_attr('sensor.zoe' , 'mileage') | int - state_attr('variable.zoe_weekly_mileage', 'last_mileage')
        | int}}
      {%- endif %}
    unit_of_measurement: "km"
    friendly_name: "Kilométrage de cette semaine"
