---
# Sensor to extract range estimation from attribute of Renault Zoé sensor
#
# https://github.com/epenet/hassRenaultZE
#
platform: template
sensors:
  zoe_remaining_range:
    value_template: "{{ state_attr('sensor.zoe' , 'remaining_range') }}"
    friendly_name: "Autonomie restante"
    unit_of_measurement: "km"
