---
# This sensor, give the textual status of the Zoé (plugged / charging)
#
# https://github.com/epenet/hassRenaultZE
# https://www.home-assistant.io/components/binary_sensor.template/
#
platform: template
sensors:
  zoe_textual_status:
    friendly_name: "État de la charge"
    value_template: >-
      {% if states('sensor.zoe') == 'unknown' -%}
      unknown
      {%- elif is_state_attr('sensor.zoe', 'plugged', true) -%}
        {%- if is_state_attr('sensor.zoe', 'charging', true) -%}
        Branchée et en charge
        {%- else -%}
        Branchée pas de charge
        {%- endif %}
      {%- else -%}
      Non Branchée
      {%- endif %}
