---
# E: This sensor, give the textual status of the Zoé (plugged / charging)
# F: Ce sensor donne un état textuel de la zoé (branchée / en charge)
#
# https://github.com/epenet/hassRenaultZE
# https://www.home-assistant.io/components/binary_sensor.template/
#
platform: template
sensors:
  zoe_textual_status:
    friendly_name: "État de la charge"
    value_template: >-
      {% if states('binary_sensor.zoe_plugged_in') == 'unknown' -%}
      unknown
      {%- elif is_state('binary_sensor.zoe_plugged_in', 'on') -%}
        {%- if is_state('binary_sensor.zoe_charging', 'on') -%}
        Branchée et en charge
        {%- else -%}
        Branchée pas de charge
        {%- endif %}
      {%- else -%}
      Non Branchée
      {%- endif %}
